### ISSUE TITLE
table.str_line() doesn't separate lines with '\n' when output is redirected to file

### ISSUE THREAD

**Issue by mhatina** [ignatenkobrain/python-smartcols#18]
When trying to split table with table.str_line() to multiple tables (with same header), it doesn't separate lines with '\n', when output is redirected to file.

Try `python reproducer > out && cat out`
[reproducer.txt](https://github.com/ignatenkobrain/python-smartcols/files/1375448/reproducer.txt)

Happens with py2 and py3.

Or maybe I am doing something wrong.

**Comment by igor-raits** [comment]
Hmm..

```
        scols_table_enable_nolinesep(self.ptr, True)
        scols_table_print_range_to_string(self.ptr, start.ptr if start is not None else NULL, end.ptr if end is not None else NULL, &data)
        scols_table_enable_nolinesep(self.ptr, False)
```

I think I've done this to make continuous printing to work. Which was implemented in dba3808d631d9092335802f45e9cb799bc2376d7.

**Comment by igor-raits** [comment]
@karelzak, can you hint me please why you have following code in continuous.c:

```c
      /* don't print line separator when in progress */
      scols_table_enable_nolinesep(tb, !done);
```

I don't see any differences when it is there or not.

**Comment by karelzak** [comment]
The libsmartcols code we print new line is:
```
        } else if (tb->no_linesep == 0 && last_in_table == 0) {
                fputs(linesep(tb), tb->out);
```
So, it depends on two things, no_linesep flag and position of the line in the table. For the last line in the table we do not print line separator at all. (I'll add this hint to docs).

In the continuous.c we always print the last line ;-) It means scols_table_enable_nolinesep(0 has no any effect there.

But if you will compose all the table before you will print it than you want it without line separators.

About redirection to file...  not sure if the continuous.c code makes sense in this case. For real application it would be probably better to print complete line with no loop to update the TIME column. It means (pseudo code):
```
  if (isatty(0))  {
     do {
          update TIME 
     } while; 
  } else if (stuff_is_complete()) {
       scols_table_print_range(tb, line, NULL);
  }
```
I'll try to improve the continuous.c to support this use-case. For now I'm not sure why all is on one line in the file.

**Comment by karelzak** [comment]
Frankly I don't know why continuous.c jumps to the new line (for done=1) if nowhere is printed \n ;-)

**Comment by karelzak** [comment]
The continuous.c example is fixed now. We need to explicitly print \n to support redirection to the file.

**Comment by igor-raits** [comment]
@karelzak my comment about continuous is not related to piping to file, it was just only one place which was using scols_table_enable_nolinesep() and I was just wondering how does it affect code =)

Thanks a lot for explanation!

**Comment by igor-raits** [comment]
@karelzak what @mhatina is trying to do:

* compose table
* split it into multiple small tables
* print them
