### ISSUE TITLE
LIBSMARTCOLS_DEBUG=all has no effect

### ISSUE THREAD

**Issue by igor-raits** [ignatenkobrain/python-smartcols#4]
## actual

```
$ LIBSMARTCOLS_DEBUG=all python3 -c "import smartcols"
```
## expected

```
$ LIBSMARTCOLS_DEBUG=all python3 -c "import smartcols"
17042: libsmartcols:     INIT: library debug mask: 0xffff
17042: libsmartcols:     INIT: library version: 2.28.0
Available "LIBSMARTCOLS_DEBUG=<name>[,...]|<mask>" debug masks:
   all      [0xffff] : info about all subsystems
   buff     [0x0040] : output buffer utils
   cell     [0x0004] : table cell utils
   col      [0x0020] : cols utils
   help     [0x0001] : this help
   line     [0x0008] : table line utils
   tab      [0x0010] : table utils
```
## proposed patch

``` diff
diff --git a/smartcols.pyx b/smartcols.pyx
index f8df415..16b8e37 100644
--- a/smartcols.pyx
+++ b/smartcols.pyx
@@ -21,6 +21,7 @@ from cpython.version cimport PY_MAJOR_VERSION
 from libc.stdlib cimport free

 cimport csmartcols
+csmartcols.scols_init_debug(0)

 cdef class Cell:
     """
```

**Comment by igor-raits** [comment]
@karelzak, is it good idea always do `scols_init_debug(0)` when you `import smartcols` or it's better to leave this option to user?

**Comment by karelzak** [comment]
That's the question :-)

We use the both ways in utils-linux (libblkid has always initialized debug, the rest of the libraries require explicit xxx_init_debug() call.

I think leave this option to user is probably more correct way. It's sometimes annoying to see that your program is doing something else and you have no way to control the behaviour (nice example is selinux-libs where code parses something in /proc).
